FROM python:3.13

RUN python -m pip install atlasopenmagic numpy matplotlib uproot awkward vector requests pika aiohttp

RUN python -c "import atlasopenmagic as atom; from atlasopenmagic import install_from_environment; install_from_environment()"

COPY . .

CMD [ "python","-u", "./Main.py"]